apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mosite-ingress
  annotations:
    cert-manager.io/cluster-issuer: cert-manager-webhook-duckdns-production
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - host: mosite.devops-demo.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mosite
            port:
              number: 80
  tls:
  - hosts:
    - mosite.devops-demo.duckdns.org
    secretName: mosite.devops-demo.duckdns.org
